---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: start webser on ubuntu
    service: 
     name: apache2
     state: started
     when: ansible_os_family=="Debian"
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="Redhat"
  - name: install webserver on redhat